apiVersion: v1
kind: Service
metadata:
  name: oracle-search
spec:
  selector:
    app: oracle-search
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP